### ISSUE TITLE
Example for generating unique addresses from a private key

### ISSUE THREAD

**Issue by 34r7h** [johnoliverdriscoll/py-edhd#1]
Hi John, I was referred to this work from the dev on pycardano. I see this repo is for learning and testing but if it's working, can you please share an example how to use it for getting a fresh address. I'll tinker and see if I can accomplish the task meanwhile. 

Thanks for providing this code! Any guidance is appreciated.

**Comment by johnoliverdriscoll** [comment]
Hello,

Please refer to the test cases for usage examples. For example, the code for deriving a BIP-32-like path can be found here: https://github.com/johnoliverdriscoll/py-edhd/blob/master/test/test_edhd.py#L40-L50

Most of the code in that block is for preparing a random key, prefix, and chaincode. The `Xprv` instance is created on line 49 and the subkey is derived on line 50.

Thanks for the interest and good luck,
JD

**Comment by 34r7h** [comment]
Awesome, thanks for the direction and pointers!
